spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/automated_ict}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Fahim.1128@}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}
spring.thymeleaf.cache=false


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fahimmontasirtuhin1128@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
