package com.example.service;

import com.example.entity.*;
import com.itextpdf.io.font.PdfEncodings;
import com.itextpdf.io.image.ImageData;
import com.itextpdf.io.image.ImageDataFactory;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.geom.Rectangle;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfPage;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.kernel.pdf.canvas.draw.SolidLine;
import com.itextpdf.layout.Canvas;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.*;
import com.itextpdf.layout.properties.HorizontalAlignment;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.Collection;
import java.util.Collections;
import java.util.List;

@Service
public class PdfService {

    public byte[] createPdf(ExamCommittee examCommittee, Semester semester, List<AssignedCourse> assignedCourses) throws IOException {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();

        try (PdfWriter writer = new PdfWriter(baos);
             PdfDocument pdfDoc = new PdfDocument(writer);
             Document document = new Document(pdfDoc)) {

            pdfDoc.setDefaultPageSize(PageSize.A4);
//            document.setMargins(70, 36, 50, 36);

            PdfFont font = PdfFontFactory.createFont("src/main/resources/fonts/times.ttf", PdfEncodings.IDENTITY_H);
            document.setFont(font);

            String logoPath = "src/main/resources/static/logo.PNG";
            ImageData imageData = ImageDataFactory.create(logoPath);
            Image logo = new Image(imageData);
            logo.setWidth(60);
            logo.setHeight(60);
           // logo.setAutoScale(true);
            logo.setHorizontalAlignment(HorizontalAlignment.CENTER);
            document.add(logo);

            addHeader(document, "Mawlana Bhashani Science and Technology University\nDept. of Information and Communication Technology, MBSTU");

            LineSeparator ls = new LineSeparator(new SolidLine(1f));
            ls.setWidth(UnitValue.createPercentValue(100));
            document.add(ls);
            addHeader(document, "Exam Committee");
            document.add(new Paragraph("\n"));

            addSemesterInfo(document, pdfDoc, semester, examCommittee);
            addCommitteeMemberTable(document, examCommittee);

            addSubHeader(document, "\nCourse Teacher\n");
            addCommitteeCourseTable(document, assignedCourses);

            addSignatureSpace(document, "-----------------------\nChairman\nDepartmental Academic Committee, Dept. of ICT, MBSTU");

            addFooter(pdfDoc, "This document has been generated by automation software. It will be considered invalid without authorized signature.");

        } catch (IOException e) {
            e.printStackTrace();
            throw e; //Re-throw the exception to let the controller handle it
        }

        //after the try block, the document is guaranteed to be closed
        return baos.toByteArray();
    }

    private void addHeader(Document document, String headerText) {
        Paragraph header = new Paragraph(headerText)
                .setTextAlignment(TextAlignment.CENTER)
                .setFontSize(18f)
                .setBold();
        document.add(header);
    }

    private void addSubHeader(Document document, String headerText) {
        Paragraph header = new Paragraph(headerText)
                .setTextAlignment(TextAlignment.CENTER)
                .setFontSize(15f)
                .setBold();
        document.add(header);
    }

    private void addSemesterInfo(Document document, PdfDocument pdfDoc, Semester semester, ExamCommittee examCommittee) throws IOException {
        StringBuilder nsb = new StringBuilder();
       // nsb.append("\n");
        nsb.append("Exam: ");
        nsb.append( examCommittee.getSemesterYearName() + " " + semester.getSemesterParity() + " Semester Final Examination - " + semester.getSemesterScheduledYear() + " \n");
        nsb.append("Session: " + examCommittee.getSession() + "\n");
        nsb.append("Held Year: " + semester.getSemesterHeldYear());
        nsb.append("\n\n");

        Paragraph paragraph = new Paragraph(nsb.toString())
                .setTextAlignment(TextAlignment.LEFT)
                .setFontSize(13f); // .setFixedPosition(30, 30, pdfDoc.getDefaultPageSize().getWidth() - 60);

        document.add(paragraph);
    }


    private void addFooter(PdfDocument pdfDoc, String text) {
        int totalPages = pdfDoc.getNumberOfPages();

        for(int i = 1; i <= totalPages; i++) {
            PdfPage page = pdfDoc.getPage(i);
            Rectangle pageSize = page.getPageSize();
            float y = 20; //footer Y position from bottom

            Canvas canvas = new Canvas(page, pageSize);

            //main footer info (centered)
            Paragraph contact = new Paragraph(text)
                    .setFontSize(10)
                    .setTextAlignment(TextAlignment.CENTER);
            canvas.showTextAligned(contact, pageSize.getWidth() / 2, y, TextAlignment.CENTER);

            //Page number (right aligned)
            Paragraph pageNum = new Paragraph("Page " + i + " of " + totalPages)
                    .setFontSize(8)
                    .setTextAlignment(TextAlignment.RIGHT);
            canvas.showTextAligned(pageNum, pageSize.getWidth() - 30, 7, TextAlignment.RIGHT);

            canvas.close();
        }
    }

    private void addCommitteeMemberTable(Document document, ExamCommittee committee) {
        Table table = new Table(UnitValue.createPercentArray(new float[]{3, 2, 2, 2, 2}));
        table.setWidth(UnitValue.createPercentValue(100));
        table.addHeaderCell(createStyledHeaderCell("Name"));
        table.addHeaderCell(createStyledHeaderCell("Designation"));
        table.addHeaderCell(createStyledHeaderCell("Dept."));
        table.addHeaderCell(createStyledHeaderCell("University"));
        table.addHeaderCell(createStyledHeaderCell("Role"));

        for (int i = 0; i < 4; i++) {
            User user = new User();
            String role = "";
            if(i == 0){
                user = committee.getChairman();
                role = "Chairman";
            }
            else if(i == 1){
                user = committee.getInternalMember1();
                role = "Internal Member";
            }
            else if(i == 2){
                user = committee.getInternalMember2();
                role = "Internal Member";
            }
            else if(i == 3){
                user = committee.getExternalMember1();
                role = "External Member";
            }

            table.addCell(createStyledCell(user.getName()));
            table.addCell(createStyledCell(user.getDesignation()));
            table.addCell(createStyledCell(user.getDepartment()));
            table.addCell(createStyledCell(user.getUniversity()));
            table.addCell(createStyledCell(role));
        }

        document.add(table);
    }

    private void addCommitteeCourseTable(Document document, List<AssignedCourse> courseList) {
        Table table = new Table(UnitValue.createPercentArray(new float[]{1.5F, 4.5F, 1.5F, 3.5F}));
        table.setWidth(UnitValue.createPercentValue(100));
        table.addHeaderCell(createStyledHeaderCell("Course Code"));
        table.addHeaderCell(createStyledHeaderCell("Course Name"));
        table.addHeaderCell(createStyledHeaderCell("Credit Hour"));
        table.addHeaderCell(createStyledHeaderCell("Assigned Teacher"));

        //Collections.sort(courseList, course_name );
        for (int i = 0; i < courseList.size(); i++) {
            AssignedCourse assignedCourse = courseList.get(i);

            table.addCell(createStyledCell(assignedCourse.getCourse().getCourse_code()));
            table.addCell(createStyledCell(assignedCourse.getCourse().getCourse_name()));
            table.addCell(createStyledCell(String.valueOf(assignedCourse.getCourse().getCourse_credit())));
            table.addCell(createStyledCell(assignedCourse.getUser().getName()));
        }

        document.add(table);
    }

    private void addSignatureSpace(Document document, String headerText) {
        Paragraph header = new Paragraph(headerText)
                .setTextAlignment(TextAlignment.LEFT)
                .setFontSize(13f)
                .setFixedPosition(40, 45, 400);
        document.add(header);
    }

    private Cell createStyledCell(String content) {
        return new Cell().add(new Paragraph(content))
                .setBackgroundColor(ColorConstants.WHITE)
                .setTextAlignment(TextAlignment.CENTER);
    }

    private Cell createStyledHeaderCell(String content) {
        return new Cell().add(new Paragraph(content))
                .setBackgroundColor(ColorConstants.LIGHT_GRAY)
                .setTextAlignment(TextAlignment.CENTER).setBold();
    }
}
